---
title: "DAF_and_other_leases_combined"
output: html_document
date: "2023-08-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#load packages I will need
```{r}
library(tidyverse)
library(here)
library(tmap)
library(sf)
library(ggplot2)
library(dplyr)
```
# load data
#Queensland leases data obtained from DAF and then ground truthed in the seascapes Lab

```{r}
qld_leases_DAF<-st_read(here("Practice_aquaculture/raw_data/QLD_aqua/Current_land_based_marine_distances.shp"))
```
# load data
#Queensland leases data obtained after  ground truthed in the seascapes Lab that are not in the list obtained from from DAF

```{r}
qld_aqua_out_of_lease<-st_read(here("Practice_aquaculture/raw_data/terrestrial_aquaculture_qld_out_of_lease/terrestrial_aquaculture_qld_out_of_lease.shp"))
```
```{r}
qld_aqua_out_of_lease<-qld_aqua_out_of_lease %>%
  dplyr::select(qldglobe_p, Area, Perimeter, geometry) %>%
  rename(qldglb_ = qldglobe_p,
         Perimtr = Perimeter)
  
```

```{r}
qld_leases_reproj<-st_transform(qld_leases_DAF, 3577)

qld_leases_reproj <- qld_leases_reproj %>%
  mutate(origin = "DAF")
```
```{r}
qld_leases_out_reproj<-st_transform(qld_aqua_out_of_lease, 3577)

qld_leases_out_reproj<-qld_leases_out_reproj %>%
  mutate(origin = "GT")
```


```{r}
qld_all_leases<- bind_rows(qld_leases_out_reproj, qld_leases_reproj)
```


